# Generated by Django 3.2.13 on 2022-06-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME_NEWS', models.CharField(max_length=30, verbose_name='NAME_NEWS')),
                ('DATA_SOURCE', models.CharField(max_length=30, verbose_name='DATA_SOURCE')),
                ('NEWS', models.TextField(verbose_name='NEWS')),
                ('DATE', models.DateTimeField(verbose_name='DATE')),
            ],
            options={
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
    ]
